# -*- coding: utf-8 -*-
"""
WHT Industrial Solver Exporters
===============================
Provides exporters for LS-DYNA (.k), Radioss (.rad), and OptiStruct (.fem).
Supports Node Sets and Element Sets mapping.
Supports Original ID preservation or Sequential Reordering.
"""

import os
import numpy as np

class IndustrialExporterBase:
    """Base class for industrial solver exporters."""
    
    def _get_mappings(self, model, reorder=False):
        """
        Generates ID mappings for nodes and elements.
        :param model: WHTMeshModel instance
        :param reorder: If True, maps to 1..N. If False, keeps original.
        :return: (node_id_map, elem_id_map)
        """
        node_ids = sorted(model.nodes.keys())
        elem_ids = sorted(model.elements.keys())
        
        if reorder:
            node_map = {nid: i+1 for i, nid in enumerate(node_ids)}
            elem_map = {eid: i+1 for i, eid in enumerate(elem_ids)}
        else:
            node_map = {nid: nid for nid in node_ids}
            elem_map = {eid: eid for eid in elem_ids}
            
        return node_map, elem_map

class LSDYNAExporter(IndustrialExporterBase):
    """Exporter for LS-DYNA Keyword format (*.k)"""
    
    def export(self, model, path, reorder=False):
        node_map, elem_map = self._get_mappings(model, reorder)
        
        with open(path, 'w', encoding='utf-8') as f:
            f.write("*KEYWORD\n")
            f.write("$# LS-DYNA Keyword file generated by WHTModeller\n")
            
            # --- Nodes ---
            f.write("*NODE\n")
            f.write("$#   nid               x               y               z\n")
            for nid in sorted(model.nodes.keys()):
                target_nid = node_map[nid]
                node = model.nodes[nid]
                x, y, z = node.x, node.y, node.z
                f.write(f"{target_nid:>10}{x:>16.8f}{y:>16.8f}{z:>16.8f}\n")
                
            # --- Elements ---
            shell_ids = [eid for eid in sorted(model.elements.keys()) if model.elements[eid].type in ["QUAD4", "TRIA3"]]
            solid_ids = [eid for eid in sorted(model.elements.keys()) if model.elements[eid].type in ["HEXA8"]]
            
            if shell_ids:
                f.write("*ELEMENT_SHELL\n")
                f.write("$#   eid     pid      n1      n2      n3      n4\n")
                for eid in shell_ids:
                    el = model.elements[eid]
                    target_eid = elem_map[eid]
                    nids = [node_map[n] for n in el.node_ids]
                    if len(nids) == 3: nids.append(nids[-1]) # TRIA3 to QUAD4 (tri)
                    f.write(f"{target_eid:>10}{1:>10}") # Placeholder PID=1
                    for n in nids: f.write(f"{n:>10}")
                    f.write("\n")
                    
            if solid_ids:
                f.write("*ELEMENT_SOLID\n")
                f.write("$#   eid     pid      n1      n2      n3      n4      n5      n6      n7      n8\n")
                for eid in solid_ids:
                    el = model.elements[eid]
                    target_eid = elem_map[eid]
                    nids = [node_map[n] for n in el.node_ids]
                    f.write(f"{target_eid:>10}{1:>10}") # Placeholder PID=1
                    for n in nids: f.write(f"{n:>10}")
                    f.write("\n")
            
            # --- Sets ---
            for sid, s in model.node_sets.items():
                f.write("*SET_NODE_LIST\n")
                set_name = str(s.name or sid)
                f.write(f"$# Set: {set_name}\n")
                f.write(f"{sid:>10}\n")
                mapped_nids = sorted([node_map[n] for n in s.node_ids])
                for i in range(0, len(mapped_nids), 8):
                    chunk = mapped_nids[i:i+8]
                    line = "".join(f"{n:>10}" for n in chunk)
                    f.write(line + "\n")
            
            f.write("*END\n")
        print(f" -> LS-DYNA file exported: {path} (reorder={reorder})")

class RadiossExporter(IndustrialExporterBase):
    """Exporter for OpenRadioss format (*.rad)"""
    
    def export(self, model, path, reorder=False):
        node_map, elem_map = self._get_mappings(model, reorder)
        
        with open(path, 'w', encoding='utf-8') as f:
            f.write("/BEGIN\n")
            f.write("Radioss input generated by WHTModeller\n")
            f.write("0 0\n")
            
            # --- Nodes ---
            f.write("/NODE\n")
            for nid in sorted(model.nodes.keys()):
                target_nid = node_map[nid]
                node = model.nodes[nid]
                x, y, z = node.x, node.y, node.z
                f.write(f"{target_nid:>10}{x:>20.10f}{y:>20.10f}{z:>20.10f}\n")
                
            # --- Elements ---
            shell_ids = [eid for eid in sorted(model.elements.keys()) if model.elements[eid].type in ["QUAD4"]]
            solid_ids = [eid for eid in sorted(model.elements.keys()) if model.elements[eid].type in ["HEXA8"]]
            
            if shell_ids:
                f.write("/QUAD\n")
                part_id = 1
                for eid in shell_ids:
                    el = model.elements[eid]
                    target_eid = elem_map[eid]
                    nids = [node_map[n] for n in el.node_ids]
                    f.write(f"{target_eid:>10}{part_id:>10}")
                    for n in nids: f.write(f"{n:>10}")
                    f.write("\n")
                    
            if solid_ids:
                f.write("/HEXA8\n")
                part_id = 1
                for eid in solid_ids:
                    el = model.elements[eid]
                    target_eid = elem_map[eid]
                    nids = [node_map[n] for n in el.node_ids]
                    f.write(f"{target_eid:>10}{part_id:>10}")
                    for n in nids: f.write(f"{n:>10}")
                    f.write("\n")
            
            # --- Node Groups ---
            for sid, s in model.node_sets.items():
                set_name = str(s.name or sid)
                f.write("/GRNOD/NODE\n")
                f.write(f"{set_name[:100]}\n")
                mapped_nids = sorted([node_map[n] for n in s.node_ids])
                for i in range(0, len(mapped_nids), 10):
                    chunk = mapped_nids[i:i+10]
                    line = "".join(f"{n:>10}" for n in chunk)
                    f.write(line + "\n")
            
            f.write("/END\n")
        print(f" -> Radioss file exported: {path} (reorder={reorder})")

class OptistructExporter(IndustrialExporterBase):
    """Exporter for Altair OptiStruct / Nastran format (*.fem)"""
    
    def export(self, model, path, reorder=False):
        node_map, elem_map = self._get_mappings(model, reorder)
        
        with open(path, 'w', encoding='utf-8') as f:
            f.write("$$ OptiStruct input generated by WHTModeller\n")
            f.write("BEGIN BULK\n")
            
            # --- Nodes ---
            for nid in sorted(model.nodes.keys()):
                target_nid = node_map[nid]
                node = model.nodes[nid]
                x, y, z = node.x, node.y, node.z
                # Fixed format GRID: GRID, ID, CP, X, Y, Z, CD, PS
                f.write(f"GRID    {target_nid:<8}        {x:<8.4f}{y:<8.4f}{z:<8.4f}\n")
                
            # --- Elements ---
            shell_ids = [eid for eid in sorted(model.elements.keys()) if model.elements[eid].type in ["QUAD4"]]
            solid_ids = [eid for eid in sorted(model.elements.keys()) if model.elements[eid].type in ["HEXA8"]]
            
            if shell_ids:
                for eid in shell_ids:
                    el = model.elements[eid]
                    target_eid = elem_map[eid]
                    nids = [node_map[n] for n in el.node_ids]
                    f.write(f"CQUAD4  {target_eid:<8}{1:<8}") # PID=1
                    for n in nids: f.write(f"{n:<8}")
                    f.write("\n")
                    
            if solid_ids:
                for eid in solid_ids:
                    el = model.elements[eid]
                    target_eid = elem_map[eid]
                    nids = [node_map[n] for n in el.node_ids]
                    f.write(f"CHEXA   {target_eid:<8}{1:<8}")
                    for n in nids[:6]: f.write(f"{n:<8}")
                    f.write("\n")
                    f.write(f"+       {nids[6]:<8}{nids[7]:<8}\n")
            
            # --- Sets ---
            for sid, s in model.node_sets.items():
                set_name = str(s.name or sid)
                f.write(f"SET, {sid}, GRID, LIST\n")
                mapped_nids = sorted([node_map[n] for n in s.node_ids])
                for i in range(0, len(mapped_nids), 8):
                    chunk = mapped_nids[i:i+8]
                    line = ", ".join(str(n) for n in chunk)
                    f.write(f", {line}\n")
            
            f.write("ENDDATA\n")
        print(f" -> OptiStruct file exported: {path} (reorder={reorder})")
