# -*- coding: utf-8 -*-
"""
WHT Industrial Solver Exporters
===============================
Provides exporters for LS-DYNA (.k), Radioss (.rad), and OptiStruct (.fem).
Supports Node Sets and Element Sets mapping.
Supports Original ID preservation or Sequential Reordering.
"""

import os
import numpy as np

class IndustrialExporterBase:
    """Base class for industrial solver exporters."""
    
    def _get_mappings(self, model, reorder=False):
        """
        Generates ID mappings for nodes and elements.
        :param model: WHTMeshModel instance
        :param reorder: If True, maps to 1..N. If False, keeps original.
        :return: (node_id_map, elem_id_map)
        """
        node_ids = sorted(model.nodes.keys())
        elem_ids = sorted(model.elements.keys())
        
        if reorder:
            node_map = {nid: i+1 for i, nid in enumerate(node_ids)}
            elem_map = {eid: i+1 for i, eid in enumerate(elem_ids)}
        else:
            node_map = {nid: nid for nid in node_ids}
            elem_map = {eid: eid for eid in elem_ids}
            
        return node_map, elem_map

class LSDYNAExporter(IndustrialExporterBase):
    """Exporter for LS-DYNA Keyword format (*.k)"""
    
    def export(self, model, path, reorder=True):
        # ALWAYS force reorder=True for industrial solvers to ensure ID consistency (1-based)
        node_map, elem_map = self._get_mappings(model, reorder=True)
        
        # Force remove existing file to avoid duplicate keyword issues caused by partial overwrites
        if os.path.exists(path):
            try:
                os.remove(path)
            except OSError:
                pass
        
        with open(path, 'w', encoding='utf-8') as f:
            f.write("*KEYWORD\n")
            f.write(f"$# Generated by WHTModeller: {model.name}\n")
            
            # --- Materials ---
            # Define a single default material if none provided to avoid part ID 0 issues
            f.write("*MAT_ELASTIC\n")
            f.write(f"$#   mid,      rho,        e,       pr\n")
            mid_def = 1
            f.write(f"{mid_def},{7.85e-9:.4e},{2.1e5:.4e},{0.3:.4f}\n")

            # --- Sections ---
            # Define a single default shell section
            f.write("*SECTION_SHELL\n")
            f.write(f"$#   sid,   elform,     shrf,      nip,    propt,  qr/irid,    icomp\n")
            sid_def = 1
            f.write(f"{sid_def},{16},{0.833:.3f},{2},{0},{0},{0}\n")
            f.write(f"{1.0:.4f},{1.0:.4f},{1.0:.4f},{1.0:.4f}\n")

            # --- Parts ---
            f.write("*PART\nTray_Component\n")
            f.write(f"$#   pid,    sid,    mid\n")
            f.write(f"{1},{sid_def},{mid_def}\n")

            # --- Nodes ---
            f.write("*NODE\n")
            f.write("$#   nid,              x,              y,              z\n")
            for nid in sorted(model.nodes.keys()):
                target_nid = node_map[nid]
                node = model.nodes[nid]
                f.write(f"{target_nid},{node.x:.8f},{node.y:.8f},{node.z:.8f}\n")
                
            # --- Elements ---
            shell_ids = [eid for eid in sorted(model.elements.keys()) if model.elements[eid].type in ["QUAD4", "TRIA3"]]
            if shell_ids:
                f.write("*ELEMENT_SHELL\n")
                f.write("$#   eid,    pid,     n1,     n2,     n3,     n4\n")
                for eid in shell_ids:
                    el = model.elements[eid]
                    target_eid = elem_map[eid]
                    # Verify all nodes exist in our map
                    try:
                        nids = [node_map[n] for n in el.node_ids]
                        if len(nids) == 3: nids.append(nids[-1])
                        f.write(f"{target_eid},{1}," + ",".join(str(n) for n in nids) + "\n")
                    except KeyError:
                        continue # Skip elements with missing nodes
                    
            # --- Sets ---
            for sid, s in model.node_sets.items():
                f.write("*SET_NODE_LIST\n")
                f.write(f"{sid}\n")
                mapped_nids = sorted([node_map[n] for n in s.node_ids if n in node_map])
                for i in range(0, len(mapped_nids), 8):
                    chunk = mapped_nids[i:i+8]
                    f.write(",".join(str(n) for n in chunk) + "\n")
            
            f.write("*END\n")
        print(f" -> LS-DYNA file exported: {path} (reorder={reorder})")

class RadiossExporter(IndustrialExporterBase):
    """Exporter for OpenRadioss format (*.rad)"""
    
    def export(self, model, path, reorder=False):
        node_map, elem_map = self._get_mappings(model, reorder)
        
        with open(path, 'w', encoding='utf-8') as f:
            f.write("/BEGIN\n")
            f.write("Radioss input generated by WHTModeller\n")
            f.write("0 0\n")
            
            # --- Nodes ---
            f.write("/NODE\n")
            for nid in sorted(model.nodes.keys()):
                target_nid = node_map[nid]
                node = model.nodes[nid]
                x, y, z = node.x, node.y, node.z
                f.write(f"{target_nid:>10}{x:>20.10f}{y:>20.10f}{z:>20.10f}\n")
                
            # --- Elements ---
            shell_ids = [eid for eid in sorted(model.elements.keys()) if model.elements[eid].type in ["QUAD4"]]
            solid_ids = [eid for eid in sorted(model.elements.keys()) if model.elements[eid].type in ["HEXA8"]]
            
            if shell_ids:
                f.write("/QUAD\n")
                part_id = 1
                for eid in shell_ids:
                    el = model.elements[eid]
                    target_eid = elem_map[eid]
                    nids = [node_map[n] for n in el.node_ids]
                    f.write(f"{target_eid:>10}{part_id:>10}")
                    for n in nids: f.write(f"{n:>10}")
                    f.write("\n")
                    
            if solid_ids:
                f.write("/HEXA8\n")
                part_id = 1
                for eid in solid_ids:
                    el = model.elements[eid]
                    target_eid = elem_map[eid]
                    nids = [node_map[n] for n in el.node_ids]
                    f.write(f"{target_eid:>10}{part_id:>10}")
                    for n in nids: f.write(f"{n:>10}")
                    f.write("\n")
            
            # --- Node Groups ---
            for sid, s in model.node_sets.items():
                set_name = str(s.name or sid)
                f.write("/GRNOD/NODE\n")
                f.write(f"{set_name[:100]}\n")
                mapped_nids = sorted([node_map[n] for n in s.node_ids])
                for i in range(0, len(mapped_nids), 10):
                    chunk = mapped_nids[i:i+10]
                    line = "".join(f"{n:>10}" for n in chunk)
                    f.write(line + "\n")
            
            f.write("/END\n")
        print(f" -> Radioss file exported: {path} (reorder={reorder})")

class OptistructExporter(IndustrialExporterBase):
    """Exporter for Altair OptiStruct / Nastran format (*.fem)"""
    
    def export(self, model, path, reorder=False):
        node_map, elem_map = self._get_mappings(model, reorder)
        
        with open(path, 'w', encoding='utf-8') as f:
            f.write("$$ OptiStruct input generated by WHTModeller\n")
            f.write("BEGIN BULK\n")
            
            # --- Nodes ---
            for nid in sorted(model.nodes.keys()):
                target_nid = node_map[nid]
                node = model.nodes[nid]
                x, y, z = node.x, node.y, node.z
                # Fixed format GRID: GRID, ID, CP, X, Y, Z, CD, PS
                f.write(f"GRID    {target_nid:<8}        {x:<8.4f}{y:<8.4f}{z:<8.4f}\n")
                
            # --- Elements ---
            shell_ids = [eid for eid in sorted(model.elements.keys()) if model.elements[eid].type in ["QUAD4"]]
            solid_ids = [eid for eid in sorted(model.elements.keys()) if model.elements[eid].type in ["HEXA8"]]
            
            if shell_ids:
                for eid in shell_ids:
                    el = model.elements[eid]
                    target_eid = elem_map[eid]
                    nids = [node_map[n] for n in el.node_ids]
                    f.write(f"CQUAD4  {target_eid:<8}{1:<8}") # PID=1
                    for n in nids: f.write(f"{n:<8}")
                    f.write("\n")
                    
            if solid_ids:
                for eid in solid_ids:
                    el = model.elements[eid]
                    target_eid = elem_map[eid]
                    nids = [node_map[n] for n in el.node_ids]
                    f.write(f"CHEXA   {target_eid:<8}{1:<8}")
                    for n in nids[:6]: f.write(f"{n:<8}")
                    f.write("\n")
                    f.write(f"+       {nids[6]:<8}{nids[7]:<8}\n")
            
            # --- Sets ---
            for sid, s in model.node_sets.items():
                set_name = str(s.name or sid)
                f.write(f"SET, {sid}, GRID, LIST\n")
                mapped_nids = sorted([node_map[n] for n in s.node_ids])
                for i in range(0, len(mapped_nids), 8):
                    chunk = mapped_nids[i:i+8]
                    line = ", ".join(str(n) for n in chunk)
                    f.write(f", {line}\n")
            
            f.write("ENDDATA\n")
        print(f" -> OptiStruct file exported: {path} (reorder={reorder})")
